# Generated by Django 4.2.1 on 2023-05-30 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_historialcompra_track'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('precio', models.IntegerField()),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.track')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.usuario')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.venta')),
            ],
        ),
    ]
