# Generated by Django 4.2.1 on 2023-05-30 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_historialcompra_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialcompra',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.track'),
        ),
        migrations.AlterField(
            model_name='historialcompra',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.venta'),
        ),
    ]
