# Generated by Django 4.2.1 on 2023-05-30 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_historialcompra_track_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='venta',
        ),
    ]
