# Generated by Django 6.0.6 on 2026-08-28 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_historialventa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='tracks'),
        ),
    ]
