# Generated by Django 6.0.6 on 2026-08-31 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_track_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpaytransaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('AUTHORIZED', 'Autorizado')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='webpaytransaction',
            name='suscripcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transacciones_webpay', to='app.suscripcion'),
        ),
    ]
