# Generated by Django 6.0.6 on 2026-08-31 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_webpaytransaction_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpaytransaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('AUTHORIZED', 'Autorizado'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20),
        ),
    ]
